version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres
    ports:
      - "5450:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin834
      POSTGRES_DB: leave_management
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./Backend
    container_name: backend
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    environment:
      - PORT=3001
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASSWORD=admin834
      - DB_NAME=leave_management
      - DB_PORT=5432
    volumes:
      - ./Backend/uploads:/app/uploads

  employee-leave:
    build: ./employee-leave
    container_name: employee-leave
    ports:
      - "8001:80"
    depends_on:
      - backend

  hr-leave:
    build: ./hr-leave
    container_name: hr-leave
    ports:
      - "8002:80"
    depends_on:
      - backend

volumes:
  pgdata:
  
